name: customer
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  firebase_core: ^3.8.1
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.3
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  dio: ^5.7.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.2.0
  flash: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/ar-EG.json
    - assets/translations/en-US.json


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/Futura-Bold.ttf
          weight: 700
        - asset: assets/fonts/futura-medium.ttf
          weight: 600
        - asset: assets/fonts/futura-medium.ttf
          weight: 500
        - asset: assets/fonts/futur-regular.ttf
          weight: 400
        - asset: assets/fonts/Futura-Light.ttf
          weight: 300