// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5sxR7aC4o_GEXlqjYZEjLmj2TXf9c6TE',
    appId: '1:445697612597:android:4e6e6faf98cb6459ad0a7c',
    messagingSenderId: '445697612597',
    projectId: 'jinni-dev-customer',
    databaseURL: 'https://jinni-dev-customer-default-rtdb.firebaseio.com',
    storageBucket: 'jinni-dev-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8iByE199LDoa5g6u61QgzxpB4a6J7EM',
    appId: '1:445697612597:ios:366260add68893b9ad0a7c',
    messagingSenderId: '445697612597',
    projectId: 'jinni-dev-customer',
    databaseURL: 'https://jinni-dev-customer-default-rtdb.firebaseio.com',
    storageBucket: 'jinni-dev-customer.appspot.com',
    androidClientId: '445697612597-1hpct3b52f7qms14codq65v261807dd2.apps.googleusercontent.com',
    iosBundleId: 'cloud.octopii.customer',
  );

}